name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: unit test
        run: npm run test:unit
